Нужно больше функций!!
htmlacademy-javascript/851543-kekstagram-25 pull request #2
Opened 2022-02-21 18:01 UTC by IgoninAleksey

2022-02-22 07:01 UTC, craz3r requested changes

2022-02-22 07:01 UTC, craz3r commented on js/main.js
> +function getRandomInt(max) {
Функция getRandomInt должна принимать 2 параметра (min, max)

Не предусмотрено поведение когда max >= min

2022-02-22 07:01 UTC, craz3r commented on js/main.js
> +console.log(`Слово "СложнА" занимает ${  string.length  } символов`);
Нужно написать **функцию** проверки строки, а не просто использовать ее свойство length

2022-02-24 09:11 UTC, craz3r requested changes

2022-02-24 09:11 UTC, craz3r commented on js/main.js
> +  return Math.floor(Math.random() * min, max);
Не реализовано поведение функции при min >= max

2022-02-24 09:11 UTC, craz3r commented on js/main.js
> +  const text = 'qwerty';
Функция square должна уметь работать с любой переданной строкой а не только с text объявленным внутри

Нужно добавить функции square параметр и работать с ним

2022-02-28 13:38 UTC, craz3r requested changes
Вижу что это уже третья неудачная проверка, может нужна консультация?

2022-02-28 13:38 UTC, craz3r commented on js/main.js
> +getRandomInt(1, 5);
Что выведет этот вызов функции? Он не сгенерирует случайное число а просто выводит в консоль true/false

2022-02-28 13:38 UTC, craz3r commented on js/main.js
> +function test (a, b = 100) {
Нужно переименовать функцию и параметры, сделать имена более осмысленными, чтобы по названию функции и именам параметров было понятно что функция делает

2022-03-03 09:55 UTC, IgoninAleksey commented
> Вижу что это уже третья неудачная проверка, может нужна консультация?
очень нужна. В скором времени попробую найти время.

2022-03-03 09:56 UTC, IgoninAleksey commented
> Вижу что это уже третья неудачная проверка, может нужна консультация?

Очень нужна. Я постараюсь найти время.

2022-03-06 13:34 UTC, craz3r requested changes

2022-03-06 13:34 UTC, craz3r commented on js/main.js
> +    console.log(true);
Функция должна **возвращать** сгенерированное число. Сейчас она просто делает console.log
Почему условие random == 20, для чего оно? Получается это функция для генерации числа 20)

2022-03-06 13:34 UTC, craz3r commented on js/main.js
> +    console.log(true);
Функция должна **возвращать** true или false в зависимости от результата выполнения. Сейчас она только делает console.log

2022-03-06 15:44 UTC, IgoninAleksey commented on js/main.js
> +    console.log(true);
Просто двадцать. Я проверял работу.

2022-03-06 18:00 UTC, IgoninAleksey commented
Так. Убрал избыточность. Облегчил ресурсозатратность убрав ненужные переменные.

2022-03-08 10:21 UTC, merged