Отрисуй меня полностью
htmlacademy-javascript/851543-kekstagram-25 pull request #5
Opened 2022-03-30 21:03 UTC by IgoninAleksey

2022-03-30 22:24 UTC, IgoninAleksey commented
![image](https://user-images.githubusercontent.com/91213379/160941072-da66bb7f-9973-4daf-a997-9b7b183a5d07.png)
Подготовил ещё такой вариант.

2022-03-31 13:31 UTC, craz3r requested changes
1. Модуль picture должен экспортировать функцию отрисовки миниатюр (сам модуль тоже лучше переименовать
2. Вставка элементов должна происходить на основе шаблонов (пример есть в [демо](https://up.htmlacademy.ru/javascript/25/demos/6315))
3. Сейчас если открыть опубликованную версию миниатюры не отображаются

2022-04-03 18:41 UTC, craz3r requested changes

2022-04-03 18:41 UTC, craz3r commented on js/picture.js
> +exportObject.forEach((elem) => {
Нужно обернуть отрисовку миниатюр в функцию и экспортировать ее из модуля picture. На будущее, модули не должны вызываться просто импортом, как сейчас сделано в модуле main. Они всегда должны что то экспортировать

2022-04-04 13:43 UTC, merged